vich_uploader:
    db_driver: orm 

    mappings:
        recettes_image:
            uri_prefix: /images/recettes
            upload_destination: '%kernel.project_dir%/public/images/recettes'

           
        users_image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'

            